#spring:
 # datasource:
  #  username: root
   # password: Harsha@123
    #url: jdbc:mysql://localhost:3306/sys
    #driver-class-name: com.mysql.cj.jdbc.Driver
  #jpa:
    #show-sql: true
    #hibernate:
      #dl-auto: update
   #properties.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
